package: d2u_immo
version: '1.1.1'
author: Tobias Krais
supportpage: http://github.com/tobiaskrais/d2u_immo

page:
    title: 'translate:d2u_immo'
    perm: d2u_immo[]
    icon: rex-icon fa-home
    subpages:
        property:
            icon: rex-icon fa-home
            title: 'translate:d2u_immo_properties'
            subpages:
                online: { title: 'translate:d2u_immo_properties_uptodate' }
                archive: { title: 'translate:d2u_immo_properties_archive' }
        category: { title: 'translate:d2u_helper_categories', icon: rex-icon rex-icon-open-category }
        contact: { title: 'translate:d2u_immo_contacts', icon: rex-icon rex-icon-user }
        settings: { title: 'translate:d2u_helper_settings', icon: rex-icon rex-icon-system, perm: d2u_immo[settings] }
        setup: { title: 'translate:d2u_helper_setup', icon: rex-icon rex-icon-install, perm: d2u_immo[settings] }

requires:
    packages:
        d2u_helper: '>=1.5.5'
        media_manager: '>=2.2'
        sprog: '>=1.0.0'
        url: '>=1.0.1'
        yform: '>=3.0'
        yrewrite: '>=2.0.1'