package: d2u_immo
version: '1.3.1'
author: Tobias Krais
supportpage: http://github.com/tobiaskrais/d2u_immo

page:
    title: 'translate:d2u_immo'
    perm: 'd2u_immo[]'
    icon: rex-icon fa-home
    subpages:
        property:
            icon: rex-icon fa-home
            title: 'translate:d2u_immo_properties'
            subpages:
                online: { title: 'translate:d2u_immo_properties_uptodate' }
                archive: { title: 'translate:d2u_immo_properties_archive' }
        category: { title: 'translate:d2u_helper_categories', icon: rex-icon rex-icon-open-category }
        contact: { title: 'translate:d2u_immo_contacts', icon: rex-icon rex-icon-user }
        settings:
            icon: rex-icon fa-navicon
            title: ''
            itemClass: pull-right
            subpages:
                settings: { title: 'translate:d2u_helper_settings', icon: rex-icon rex-icon-system, perm: 'd2u_immo[settings]' }
                setup: { title: 'translate:d2u_helper_setup', icon: rex-icon rex-icon-install, perm: 'd2u_immo[settings]' }
                help: { title: 'translate:package_hhelp', icon: rex-icon rex-icon-help }
                changelog: { title: 'translate:d2u_helper_help_chapter_changelog', icon: rex-icon fa-files-o }

requires:
    redaxo: '>=5.15.0'
    packages:
        d2u_helper: '>=1.14.0'
        media_manager: '>=2.2'
        sprog: '>=1.0.0'
        url: '>=2.0'
        yform: '>=3.0'
        yrewrite: '>=2.0.1'
    php: '>=8.0'

default_config:
    default_category_sort: 'name'
    default_property_sort: 'name'
    finance_calculator_interest_rate: '0.018'
    finance_calculator_notary_costs: '0.015'  
    finance_calculator_real_estate_tax: '0.05'  
    finance_calculator_repayment: '0.04'

installer_ignore:
    - .github